title: OMID KOKABEE
description: Personal website, research, professional work and daily notes
theme: minima

header_pages:
  - index.md
  - about.md
  - research.md
  - projects.md
  - blog.md
  - contact.md
